name: Cross-platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential automake libtool

      - name: Build
        run: |
          ./bootstrap.sh
          ./configure
          make -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iperf3-linux
          path: src/iperf3

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install automake libtool

      - name: Build
        run: |
          ./bootstrap.sh
          ./configure
          make -j$(sysctl -n hw.ncpu)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iperf3-macos
          path: src/iperf3

  build-windows-matrix:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86_64, i686]  # 64-bit and 32-bit Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW${{ matrix.arch == 'x86_64' && '64' || '32' }}
          update: true
          install: >-
            base-devel
            mingw-w64-${{ matrix.arch }}-toolchain
            mingw-w64-${{ matrix.arch }}-crt
            automake
            libtool
            make

      - name: Configure and Build
        shell: msys2 {0}
        run: |
          ./bootstrap.sh
          ./configure --host=${{ matrix.arch }}-w64-mingw32 ac_cv_search_socket="-lws2_32" ac_cv_search_inet_ntop=""
          make -j$(nproc)

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: iperf3-windows-${{ matrix.arch }}
          path: src/iperf3.exe
